### PR TITLE
unifyfs utility to wait until all servers become ready.

### LINKED ISSUE #505: LSB_MCPU_HOSTS includes a space that causes incorrect node count in the unifyfs utility
### System information
Summit

### Describe the problem you're observing
The `LSB_MCPU_HOSTS` env string has an extra space character at the end, which causes the `unifyfs` utility incorrectly counts extra node as available compute node.

### Describe how to reproduce the problem
Submit the job in Summit with requesting a sufficient number of nodes (e.g., 16). When the number of compute nodes are small (e.g., <= 8), `LSB_HOSTS` is read from `unifyfs`, while `LSB_MCPU_HOSTS` is used for larger number of nodes.

### Include any warning or errors or releveant debugging data
Running a job with 4 nodes (instrumented some debugging messages in `lsb_read_resource()`):

```
WARNING: cleanup not yet supported!
LSB_HOST (mcpu=0): batch3 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09
lsb_hosts: batch3 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n14 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n15 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 c05n16 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09 g19n09
n_nodes = 4 (skip first)
final node list (4 nodes): c05n14, c05n15, c05n16, g19n09
```

Running a job with 16 nodes (extra space counted as a node, `n_nodes` becoming 17):

```
WARNING: cleanup not yet supported!
LSB_MCPU_HOSTS (mcpu=1): batch2 1 c12n16 42 c12n17 42 c12n18 42 h20n06 42 h20n07 42 h20n08 42 h20n09 42 h20n10 42 h20n11 42 h20n12 42 h20n13 42 h20n14 42 h20n15 42 h20n16 42 h20n17 42 h20n18 42 
lsb_hosts: batch2 1 c12n16 42 c12n17 42 c12n18 42 h20n06 42 h20n07 42 h20n08 42 h20n09 42 h20n10 42 h20n11 42 h20n12 42 h20n13 42 h20n14 42 h20n15 42 h20n16 42 h20n17 42 h20n18 42 
n_nodes = 17 (skip first)
final node list (17 nodes): c12n16, c12n17, c12n18, h20n06, h20n07, h20n08, h20n09, h20n10, h20n11, h20n12, h20n13, h20n14, h20n15, h20n16, h20n17, h20n18, 
Error: nrs (17) should not be greater than rs_per_host (1) * number of servers available (16).
Error: Requested job constraints can never be met. Job was not scheduled. Check your request and try again.
ERROR: failed to wait for server initialization
```

### PR DESCRIPTION
**Pull request by sandrain**
unifyfs utility to wait until all servers become ready.
- unifyfsd publishes a server pid file (unifyfsd.pids) under the shared
state state directory, indicating that all servers are ready
- unifyfs utility blocks until the pid file appears

Also, this includes an additional commit that fixes #505.

TEST_CHECKPATH_SKIP_FILES=common/src/unifyfs_configurator.h

### Description
This addresses #499.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Testing (addition of new tests or update to current tests)
- [ ] Documentation (a change to man pages or other documentation)

### CODE REVIEW

File: server/src/unifyfs_server_pid.c [hunk 1]
```diff
@@ -0,0 +1,207 @@
...
+                goto out_free;
+            }
+        }
+
+        ret = create_server_pid_file();
+        if (UNIFYFS_SUCCESS == ret) {
+            LOGDBG("all servers are ready to accept client connection");
+        }
+
+out_free:
```
Comment (MichaelBrim) [inline server/src/unifyfs_server_pid.c:200]: instead of having two labels at the end of this function, just use one like this:
```
out:
    if (NULL != server_pids) {
        free(server_pids);
    }
    return  ret;
```

File: server/src/unifyfs_server_pid.c [hunk 2]
```diff
@@ -0,0 +1,207 @@
...
+    if (count == glb_pmi_size) {
+        ret = pthread_cond_signal(&server_pid_cond);
+        if (ret) {
+            LOGERR("failed to signal condition (%s)", strerror(ret));
+        }
+    }
+}
+DEFINE_MARGO_RPC_HANDLER(server_pid_handle_rpc);
+
+static int set_timeout(void)
```
Comment (MichaelBrim) [inline server/src/unifyfs_server_pid.c:112]: suggest making this 'static inline'

**Comment by sandrain** [comment]
Not sure why spack fails during CI build:

```
before_install.1
4610.00s$ test -n $CC && unset CC
before_install.2
46212.42s$ (cd $HOME/spack; git describe) || git clone https://github.com/spack/spack $HOME/spack
before_install.3
4710.00s$ test -f $HOME/spack/etc/spack/packages.yaml || cat > $HOME/spack/etc/spack/packages.yaml << '  EOF'
4970.53s$ $HOME/spack/bin/spack bootstrap
498==> Error: bootstrap is not a recognized Spack command or extension command; check with `spack commands`.
499The command "$HOME/spack/bin/spack bootstrap" failed and exited with 1 during .
```

File: server/src/unifyfs_server_pid.c [hunk 3]
```diff
@@ -0,0 +1,207 @@
...
+    return 0;
+}
+
+static int create_server_pid_file(void)
+{
+    int i = 0;
+    int ret = 0;
+    char filename[PATH_MAX] = { 0, };
+    FILE* fp = NULL;
+
```
Comment (MichaelBrim) [inline server/src/unifyfs_server_pid.c:138]: even though this should only be called when `server_pids` has been setup correctly, it's still better to check that it's not NULL before accessing it

File: util/unifyfs/src/unifyfs-rm.c [hunk 4]
```diff
@@ -807,11 +869,25 @@ int unifyfs_start_servers(unifyfs_resource_t* resource,
         return rc;
     }
 
-    if (args->script != NULL) {
-        return script_launch(resource, args);
-    } else {
-        return resource_managers[resource->rm].launch(resource, args);
+    pid = fork();
+    if (pid < 0) {
+        fprintf(stderr, "failed to launch the server process (%s)\n",
```
Comment (MichaelBrim) [inline util/unifyfs/src/unifyfs-rm.c:874]: error message isn't quite accurate. how about "failed to create the server launch process"?

File: server/src/unifyfs_server_pid.c [hunk 5]
```diff
@@ -0,0 +1,207 @@
+/*
+ * Copyright (c) 2017, Lawrence Livermore National Security, LLC.
```
Comment (MichaelBrim) [inline server/src/unifyfs_server_pid.c:2]: suggest updating copyright year to 2020 for new files

File: server/src/unifyfs_global.h [hunk 6]
```diff
@@ -197,5 +198,13 @@ unifyfs_rc disconnect_app_client(app_client* clnt);
 
 unifyfs_rc cleanup_app_client(app_client* clnt);
 
+/**
```
Comment (MichaelBrim) [inline server/src/unifyfs_global.h:201]: Since `unifyfs_publish_server_pids()` is only used in `server/src/unifyfs_server.c`, I suggest you move this declaration to that file.

**Comment by sandrain** [comment]
@MichaelBrim Thanks for comments. I will make changes accordingly.

File: server/src/unifyfs_global.h (hunk 6 above)
Comment (sandrain) [reply server/src/unifyfs_global.h:201]: I initially did that but guess checkpatch script was not happy. I will check it again.

File: common/src/unifyfs_configurator.h [hunk 7]
```diff
@@ -90,6 +90,7 @@
     UNIFYFS_CFG_CLI(runstate, dir, STRING, RUNDIR, "runstate file directory", configurator_directory_check, 'R', "specify full path to directory to contain server runstate file") \
     UNIFYFS_CFG_CLI(server, hostfile, STRING, NULLSTRING, "server hostfile name", NULL, 'H', "specify full path to server hostfile") \
     UNIFYFS_CFG_CLI(sharedfs, dir, STRING, NULLSTRING, "shared file system directory", configurator_directory_check, 'S', "specify full path to directory to contain server shared files") \
+    UNIFYFS_CFG_CLI(server, init_timeout, INT, UNIFYFS_DEFAULT_INIT_TIMEOUT, "timeout of waiting for server initialization", NULL, 't', "timeout in seconds to wait for servers to be ready for clients") \
```
Comment (CamStan) [inline common/src/unifyfs_configurator.h:93]: Mind adding this to our docs ([here](https://unifyfs.readthedocs.io/en/latest/configuration.html#id7)) with a note on what the default is?

E.g.: timeout in seconds to wait for servers to be ready for clients (default: 120)

Comment (sandrain) [reply common/src/unifyfs_configurator.h:93]: @CamStan I will add it

File: server/src/unifyfs_server_pid.c [hunk 8]
```diff
@@ -0,0 +1,213 @@
...
+
+    if (glb_pmi_rank > 0) {
+        ret = server_pid_invoke_rpc();
+        if (ret) {
+            LOGERR("failed to invoke pid rpc (%s)", strerror(ret));
+        }
+    } else {
+        ret = set_timeout();
+        if (ret) {
+            goto out;
```
Comment (MichaelBrim) [inline server/src/unifyfs_server_pid.c:176]: no need for goto here, just `return ret`

File: server/src/unifyfs_server_pid.c [hunk 9]
```diff
@@ -0,0 +1,213 @@
...
+        }
+
+        server_pids = calloc(glb_pmi_size, sizeof(*server_pids));
+        if (!server_pids) {
+            LOGERR("failed to allocate memory (%s)", strerror(errno));
+            goto out;
```
Comment (MichaelBrim) [inline server/src/unifyfs_server_pid.c:182]: no need for goto here, just `return ENOMEM`

File: server/src/unifyfs_server_pid.c [hunk 10]
```diff
@@ -0,0 +1,213 @@
...
+        goto out;
+    }
+
+    for (i = 0; i < glb_pmi_size; i++) {
+        fprintf(fp, "[%d] %d\n", i, server_pids[i]);
+    }
+
+    fclose(fp);
+
+out:
```
Comment (MichaelBrim) [inline server/src/unifyfs_server_pid.c:160]: you should only use labels when there is common code that must be run at the end of the function in many cases. this function has no such code. replace all your gotos with explicit returns.

**Comment by sandrain** [comment]
@MichaelBrim Thanks. I've removed unnecessary goto statements. I've also added code to unlink existing pid file (somehow if any) before launch the servers.

I am wondering if there exist any use-case that a user starts unifyfsd twice in a single job? For instance:

```
unifyfs start 
jsrun/srun /some/app
unifyfs terminate

unifyfs start
jsrun /some/other/independent/app
unifyfs terminate
```

I am just thinking if we need to have cleanup routines (shm, etc. #496) when we terminate the server.

**Comment by MichaelBrim** [comment]
@sandrain, regarding cleanup. When the servers shutdown cleanly they will remove all the state correctly. It's the failed server runs (e.g., segfaults) that are problematic. For your example, I assume the first instance ran successfully, so there should be no issue starting up the second instance.

File: server/src/unifyfs_server_pid.c [hunk 11]
```diff
@@ -0,0 +1,210 @@
...
+    in.rank = glb_pmi_rank;
+    in.pid = server_pid;
+
+    hret = margo_create(unifyfsd_rpc_context->svr_mid,
+                        glb_servers[0].margo_svr_addr,
+                        unifyfsd_rpc_context->rpcs.server_pid_id,
+                        &handle);
+    if (hret != HG_SUCCESS) {
+        LOGERR("failed to create rpc handle (ret=%d)", hret);
+        return EIO;
```
Comment (MichaelBrim) [inline server/src/unifyfs_server_pid.c:50]: These `EIO` return codes should be `UNIFYFS_ERROR_MARGO`.

File: server/src/unifyfs_server_pid.c [hunk 12]
```diff
@@ -0,0 +1,210 @@
...
+        }
+
+        ret = create_server_pid_file();
+        if (UNIFYFS_SUCCESS == ret) {
+            LOGDBG("all servers are ready to accept client connection");
+        }
+    }
+out:
+    if (server_pids) {
+        free(server_pids);
```
Comment (MichaelBrim) [inline server/src/unifyfs_server_pid.c:205]: After free(), you should set `server_pids` back to NULL.

**Comment by sandrain** [comment]
@MichaelBrim I have included an additional commit to fix #505.
